modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="boss_tools"
version="Released"
displayName="boss tools"
credits="Made by MrScautHD"
displayURL="https://www.curseforge.com/minecraft/mc-mods/space-bosstools"
authors="MrScautHD"

[[dependencies.boss_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




